-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM (SELECT A.INGREDIENT_TYPE, B.TOTAL_ORDER
FROM ICECREAM_INFO A, 
    ( 
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF
        GROUP BY FLAVOR
    ) B 
WHERE A.FLAVOR = B.FLAVOR ) C
GROUP BY INGREDIENT_TYPE